//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WifiShare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WifiShare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password for {0} has been copied to clipboard..
        /// </summary>
        internal static string ActionCopied {
            get {
                return ResourceManager.GetString("ActionCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords for networks: {0} has been copied to clipboard..
        /// </summary>
        internal static string ActionCopiedMany {
            get {
                return ResourceManager.GetString("ActionCopiedMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has ben exported to file {0}..
        /// </summary>
        internal static string ActionExported {
            get {
                return ResourceManager.GetString("ActionExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List loaded..
        /// </summary>
        internal static string ActionLoaded {
            get {
                return ResourceManager.GetString("ActionLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string ErrorInfo {
            get {
                return ResourceManager.GetString("ErrorInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wifishare_logs.
        /// </summary>
        internal static string LogDir {
            get {
                return ResourceManager.GetString("LogDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wifi_credentials.
        /// </summary>
        internal static string TempDir {
            get {
                return ResourceManager.GetString("TempDir", resourceCulture);
            }
        }
    }
}
